Fixed RoleConverter (#15)
+ Used different approach to deserialize to prevent
System.InvalidOperationException: 'Cannot skip tokens on partial JSON.
Either get the whole payload and create a Utf8JsonReader instance where
isFinalBlock is true or call TrySkip.'
+ Serialization of SelectionRole is now complete
+ Serialization of Users property added (was missing)

Co-authored-by: Ivan Lieckens <ivanlieckens@hotmail.com>